#include "phenotype.h"

// Constructor:

// Initialization constructor.
Phenotype::Phenotype(Organism* organism_)
{
    // Assigns this `Phenotype` to an `Organism`.
    organism = organism_;
}


// Methods:

// Assembles this `Phenotype`.
void Phenotype::assemble()
{
    // Disassembles this `Phenotype` prior to assemblage.
    this->disassemble();

    // Assembles all RECURRENT and LOOPED `Link`s.
    for (const auto& theLink_ : organism->genotype->links->retrieve({RECURRENT, LOOPED}, {ENABLED}))
    {
        // Connects the current `Link` to its corresponding target `Node`.
        theLink_->outNode->inLinks.push_back(theLink_);
    }

    // Assembles all FORWARD and BIASING `Link`s.
    for (const auto& theLink_ : organism->genotype->links->retrieve({FORWARD, BIASING}, {ENABLED}))
    {
        // Connects the source and target `Node`s joined by the current `Link`.
        theLink_->outNode->inLinks.push_back(theLink_);
        theLink_->inNode->outLinks.push_back(theLink_);
    }

    return;
}

// Disassembles this `Phenotype`.
void Phenotype::disassemble()
{
    // Deactivates this `Phenotype` prior to disassemblage.
    this->deactivate();

    // Disassembles all `Link`s stemming from INPUT and BIAS `Node`s.
    for (const auto& theNode_ : organism->genotype->nodes->retrieve({INPUT, BIAS}, {ENABLED}))
    {
        // Disconnects all `Link`s stemming from the current `Node`.
        theNode_->outLinks.clear();
    }

    // Disassembles all `Link`s stemming from and arriving at HIDDEN and OUTPUT `Node`s.
    for (const auto& theNode_ : organism->genotype->nodes->retrieve({HIDDEN, OUTPUT}, {ENABLED}))
    {
        // Disconnects all `Link`s stemming from and arriving at the current `Node`.
        theNode_->inLinks.clear();
        theNode_->outLinks.clear();
    }

    return;
}

// Propagates an input signal through this `Phenotype` and stores its output.
void Phenotype::activate(std::vector<double> inputs_)
{
    // Engages all RECURRENT and LOOPED `Link`s.
    for (const auto& theLink_ : organism->genotype->links->retrieve({RECURRENT, LOOPED}, {ENABLED}))
    {
        // Engages the current RECURRENT or LOOPED `Link`.
        theLink_->engage();
    }

    // Engages all INPUT and BIAS `Node`s, recursively triggering all other `Node`s to be engaged as well.
    for (const auto& theNode_ : organism->genotype->nodes->sort({INPUT, BIAS}, {ENABLED}))
    {
        // Engages the current INPUT or BIAS `Node`.
        theNode_->inputs.push_back(inputs_.at(theNode_->tag));
        theNode_->engage();
    }

    // Extracts this `Phenotype`'s output.
    for (const auto& theNode_ : organism->genotype->nodes->sort({OUTPUT}, {ENABLED}))
    {
        // Stores the latest output signal generated by the current OUTPUT `Node`.
        output.push_back(theNode_->output);
    }

    return;
}

// Restores this `Phenotype` to a clean slate.
void Phenotype::deactivate()
{
    // Disengages all ENABLED `Node`s.
    for (const auto& theNode_ : organism->genotype->nodes->retrieve({INPUT, BIAS, HIDDEN, OUTPUT}, {ENABLED}))
    {
        // Disengages the current `Node`.
        theNode_->disengage();
    }

    // Clears this `Phenotype`'s output.
    output.clear();

    return;
}
